<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.3 setup script
 * Date: Thu, 19 Jun 2014 23:39:57 +0900
 */

/* Servers configuration */
$i = 0;

/* Server: sddb0040027077.cgidb [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'sddb0040040144.cgidb';
$cfg['Servers'][$i]['host'] = 'sddb0040040144.cgidb';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = true;
$cfg['blowfish_secret'] = '53a2f5e3cb3ba2.34001328';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
?>