/**
 * definition of database
 */

-- tweets 

DROP TABLE IF EXISTS tweets;
CREATE TABLE tweets (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , tweet VARCHAR(64) NOT NULL
  , stuff VARCHAR(64) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE tweets AUTO_INCREMENT = 1001;


-- snaps 

DROP TABLE IF EXISTS snaps;
CREATE TABLE snaps (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , name VARCHAR(64) NOT NULL
  , memo VARCHAR(1024) NOT NULL
  , stuff VARCHAR(64) NOT NULL
  , sex INTEGER
  , category INTEGER
  , file_path VARCHAR(64) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE snaps AUTO_INCREMENT = 1001;


-- schedules

DROP TABLE IF EXISTS schedules;
CREATE TABLE schedules (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , date DATE NOT NULL
  , stuff VARCHAR(64) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE schedules AUTO_INCREMENT = 1001;
