DROP TABLE IF EXISTS users;

-- ユーザー

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , email VARCHAR(128) NOT NULL
  , password VARCHAR(128) NOT NULL
  , last_name VARCHAR(128) NOT NULL
  , first_name VARCHAR(128) NOT NULL
  , role VARCHAR(32) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE users AUTO_INCREMENT = 1001;


-- トピックス

DROP TABLE IF EXISTS topics;

CREATE TABLE topics (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , date DATE NOT NULL
  , title VARCHAR(1024)
  , content VARCHAR(2048) NOT NULL
  , uri VARCHAR(2048)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE topics AUTO_INCREMENT = 1001;


-- ファイル

DROP TABLE IF EXISTS files;

CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , file_path VARCHAR(1024)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE files AUTO_INCREMENT = 1001;


-- ログ

DROP TABLE IF EXISTS logs;

CREATE TABLE logs (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , ip VARCHAR(128)
  , user VARCHAR(128)
  , action VARCHAR(128)
  , browser VARCHAR(1024)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE logs AUTO_INCREMENT = 1001;
