DROP TABLE IF EXISTS contacts;

CREATE TABLE contacts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , name VARCHAR(1024)
  , area VARCHAR(1024)
  , email VARCHAR(1024)
  , tel VARCHAR(1024)
  , content VARCHAR(2048) NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE contacts AUTO_INCREMENT = 1001;
