DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS tweets;
DROP TABLE IF EXISTS snaps;
DROP TABLE IF EXISTS schedules;

CREATE TABLE news (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , date DATE NOT NULL
  , title VARCHAR(1024)
  , content VARCHAR(2048) NOT NULL
  , uri VARCHAR(2048)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE news AUTO_INCREMENT = 1001;

CREATE TABLE tweets (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , stuff INTEGER
  , tweet VARCHAR(1024)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE tweets AUTO_INCREMENT = 1001;

CREATE TABLE snaps (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , name VARCHAR(1024)
  , sex INTEGER
  , stuff INTEGER
  , file_path VARCHAR(1024)
  , category INTEGER
  , memo VARCHAR(2048)
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE snaps AUTO_INCREMENT = 1001;

CREATE TABLE schedules (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , date DATE NOT NULL
  , stuff INTEGER
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE schedules AUTO_INCREMENT = 1001;
