DROP TABLE IF EXISTS coupons;

CREATE TABLE coupons (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , title VARCHAR(1024)
  , content VARCHAR(2048) NOT NULL
  , target INTEGER NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
ALTER TABLE coupons AUTO_INCREMENT = 1001;
